name = "aggregator-receiver"
main = "src/index.js"
compatibility_date = "2025-04-04"

# Optional KV binding if you want to persist
# [[kv_namespaces]]
[[kv_namespaces]]
binding = "Agg_MESSAGES"
id = "59ee1f7ae9444808be0d30a0837fedb8"
